create table if not exists rules (
    id bigint generated by default as identity primary key,
    address_pattern varchar(320) not null,
    subject_regex varchar(1000),
    target_folder varchar(255) not null
);

alter table rules add column if not exists subject_regex varchar(1000);

update rules
set target_folder = concat('/', target_folder)
where target_folder not like '/%';
